# -*- coding: utf-8 -*-
"""Rag project Resume .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13fSOuSt_eaT2U033kz8eu5YUj_DOEV-8
"""

! pip install -U langchain langchain-community Pypdf huggingface  faiss-cpu

! pip install -U transformers pipeline

from google.colab import files
Document=files.upload()

! pip install -U langchain langchain-community

"""load pdf

"""

from langchain_community.document_loaders import PyPDFLoader
loader=PyPDFLoader("Harsh DataAnalytics.pdf (1) (1).pdf")
documents=loader.load()

"""chunking"""

from langchain_text_splitters import RecursiveCharacterTextSplitter
splitter=RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50
)
docs=splitter.split_documents(documents)

"""Create Embedding"""

from langchain_community.embeddings import HuggingFaceEmbeddings
embeddings=HuggingFaceEmbeddings(model_name="sentence-Transformers/all-MiniLM-L6-V2")

"""STORE IN FAISS"""

from langchain_community.vectorstores import FAISS
vector_db=FAISS.from_documents(docs,embeddings)

"""QUERY WITH JOB DESCRIPTION"""

job_desc="Looking for Python, ML, SQL, NLP experiance"
retrieved_docs=vector_db.similarity_search(job_desc,k=3)

"""PASS TO LLM(RAG)"""

from transformers import pipeline
llm=pipeline("text-generation",model="tiiuae/falcon-7b-instruct")
context=" ".join([doc.page_content for doc in retrieved_docs])
prompt=f"""
Resume Context:
{context}

Job Description:
{job_desc}

Give:
1.Match Scor(%)
2.Missing Skills
3.Suggestions
"""
result=llm(prompt)
print(result[0]['generated_text'])

